config/routes.rb
Rails.application.routes.draw do
  
  get '/signup' => "users#new", :as => "signup"
  get '/login' => "sessions#new", :as => "login"
  post '/sessions' => "sessions#create"
  get '/logout' => "sessions#destroy"
  get '/auth/:provider/callback' => 'sessions#create'
  
  put 'completed_item', to: 'items#complete', as: :completed_item
  get 'completed_most', to: 'users#show_completed', as: :completed_most

  resources :users, :only => [:new, :create] #<-- created 7 restful routes but only allows 2(new and create)

  resources :lists do 
    resources :items
  end


  root 'welcome#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :list
    belongs_to :user
    
    validates :description, presence: true

    STATUS = {
        :incomplete => false,
        :complete => true
    }
    
    def complete?
        self.status == STATUS[:complete]
    end

    def incomplete?
        self.status == STATUS[:complete]
    end

    def self.complete
        where(status: true).order('id DESC')
    end

    def self.incomplete
        where(status: false).order('id DESC')
    end

end

app/models/list.rb
class List < ApplicationRecord
    has_many :items
    has_many :users, :through => :items

    validates :name, presence: true
    

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :items_completed, -> {complete}, class_name: "Item"

    validates :email, :presence => true
    validates :email, :uniqueness => true
    
    scope :most_completed_items, -> {order(items_completed_count: :desc).first}
    scope :second_most_completed_items, -> {order(items_completed_count: :desc).all[1..-1]}

    has_many :items
    has_many :lists, :through => :items


    def self.find_or_create_by_omniauth(auth_hash)
        #Login with github
        self.where(:email => auth_hash["info"]["email"]).first_or_create do |user|
            user.password = SecureRandom.hex
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    def authentication_required
        if !logged_in?
            redirect_to login_path
        end
    end

    def logged_in?
        !!current_user #<-- automatically reloads user in the request cycle
    end

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authentication_required

  def create
    @item = @list.items.build(item_params)
    @item.user_id = current_user.id
      if @item.save
        @list.items << @item
      end
        redirect_to [current_user, @list]
    end
  end

  def update #patch - /lists/:list_id/items/:item_id
    @item = Item.find(params[:id])
    @item.user_id = current_user.id
      if @item.update(item_params)
        redirect_to list_path(@item.list)
      else
        render "lists/show"
      end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.user_id = current_user.id
      if @item.destroy
        redirect_to list_path(@item.list)
      else
        render "lists/show"
      end
  end

  def complete
    Item.where(id: params[:item_ids]).update_all(status: true)
    current_user.items_completed_count +=(params[:item_ids].count)
    current_user.save

    redirect_to_items_path(current_user.id)
  end

  private

    def item_params
      params.require(:item).permit(:description, :status)
    end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    before_action :authentication_required

    def index 
        @list = List.new #<-- the new form(def new)
        @lists = List.all
        
    end

    def show
        #data passed by user // /lists/:id thanks to params[:id]
        @list = List.find(params[:id])
        @item = Item.new
    end

    def create
        @list = List.new(list_params)
        if @list.save
            redirect_to list_url(@list)
        else
            @lists = List.all 
            render :index
        end
    end

    def destroy
        @list = List.find(params[:id])
        if @list.present?
            @list.destroy
        end
            redirect_to lists_path

    end

    def edit
        @list = List.find(params[:id])
    end

    def update
        @list = List.find(params[:id])
        @list.update(list_params)

        redirect_to (@list), notice: "Updated!"
    end
    
    private

        def list_params #strong params
            params.require(:list).permit(:name)
        end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new

    end

    def create
        if auth_hash = request.env["omniauth.auth"]
            user = User.find_or_create_by_omniauth(auth_hash)
            session[:user_id] = user.id

            redirect_to root_path
        else
            #Normal login username/pass
            user = User.find_by(:email => params[:email])
            if user && user.authenticate(params[:password])
                session[:user_id] = user.id

                redirect_to root_path
            else
                render 'sessions/new'
            end
        end
    end

    def destroy
        reset_session
        redirect_to login_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new
        @user.email = params[:user][:email]
        @user.password = params[:user][:password]

        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path
        else
            render 'users/new' #<-- show the form again
        end
    end

    def show_completed
        @featured_user = User.most_completed_items
        @most_completed_users = User.second_most_completed_items
    end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
    def li_class_for_item(item)
        "completed" if item.complete?
    end

    def li_for_item(item)
        content_tag_for :li, item, :class => li_class_for_item(item) do
            yield
        end
    end

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_item_li.html.erb
<%= li_for_item(item) do %>

    <%= form_for([@list, item]) do |f| %>

    <div class="view">
        <%= f.check_box :status, :class => "toggle", :checked => item.complete? %>
    <% end %>
        <label><%= item.description %></label>

        
    <%= button_to "x", list_item_path(item.list, item), :method => "delete", :class => "destroy" %>
        
    </div>

<% end %>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Activities</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
    
  </body>
</html>

app/views/lists/_form.html.erb
<h1>Edit Activity</h1>
<%= form_for([current_user, @list]) do |f| %>
    <%= f.text_field :name, :class => "new-todo", :placeholder => (@list.errors.full_messages_for(:name).first || "Enter a new Activity") %>
    <%= f.submit :style=> "display: none" %>
<% end %>

app/views/lists/edit.html.erb
<%= render 'form' %>

app/views/lists/index.html.erb
<section class="todoapp">
    <header class="header">
        <h1>Activities</h1>
        <%= form_for(@list) do |f| %>
            <%= f.text_field :name, :class => "new-todo", :placeholder => (@list.errors.full_messages_for(:name).first || "Enter a new Activity") %>
            <%= f.submit :style => "display: none" %>
        <% end %>
    </header>

      <section class="main">
        <input class="toggle-all" type="checkbox">
        <label for="toggle-all">Mark all as complete</label>
        <ul class="todo-list">
            <% @lists.each do |list| %>
            <li>
                <div class="view">
                    <label><%= link_to list.name, list_path(list) %></label>
                </div>
            </li>
            <% end %>
        </ul>
      </section>

      <footer class="footer">
      </footer>
</section>

<footer class="info">
    <%= link_to "Most Completed", completed_most_path(@user) %>
    <p>You're logged in as: <%= current_user.email %></p>
    <p><%= link_to "Logout", logout_path %></p>
</footer>

app/views/lists/show.html.erb
<section class="todoapp">
    <header class="header">
        <h1><%= @list.name %></h1>
        <%= form_for([@list, @item]) do |f| %>
            <%= f.text_field :description, :class => "new-todo", :placeholder => (@item.errors.full_messages_for(:description).first || "Enter a new item") %>

            <%= f.submit :style => "display: none" %>

        <% end %>
      </header>


      <section class="main">
        <input class="toggle-all" type="checkbox">
        <label for="toggle-all">Mark all as complete</label>
        <ul class="todo-list">
            <%= render :collection => @list.items, :partial => "items/item_li", :as => :item %>
            <br>
            <%= button_to "Delete", list_path(@list), :method => "delete", :class => "destroy" %>
            <br>
            <%= link_to 'Back', lists_path(@list) %>
        </ul>
      </section>

      <footer class="footer">
      </footer>
</section>

app/views/users/_completed.html.erb
<h3> Status of who has done what</h3>
    <h1> Featured User </h1>
    <h2><%= featured_user.email %> has completed the most (<%= featured_user.items.complete.size %>) activities! </h2>
    
    <% for user in @most_completed_users %>
        <%= user.email %> has completed <%= user.items.complete.size %> activities. 
        <br>
    <% end %>

    <%= link_to 'Back to activities list', lists_path(@list) %>

app/views/users/new.html.erb
<section class="todoapp">
    <header class="header">
        <h1>Sign Up</h1>
        <%= form_for(@user) do |f| %>
            <%= f.text_field :email, :class => "new-todo", :placeholder => "Register with an email" %>
            <%= f.text_field :password, :class => "new-todo", :placeholder => "Please enter a password" %>
            <%= f.submit %>
        <% end %>


    </header>



    <footer class="footer">
    </footer>
</section>

app/views/users/show_completed.html.erb
<%= render partial: 'completed',
    locals: {
        featured_user: @featured_user,
        most_completed_users: @most_completed_users
    } %>

app/views/welcome/index.html.erb
<% if current_user %>
    <h4> Click here <%= link_to "Your Lists", lists_path(current_user, @list) %></h4>
    <br>
        <p> You're logged in as: <%= current_user.email %></p>
        <p><%= link_to "Logout", logout_path %></p>
    <%else %>
        <%= link_to "Signup", new_user_path(@user) %>
        <br>
        <%= link_to "Login", login_path %>
        <br>
    <h3>Login with Github</h3>
    Use <%= link_to "Github", "/auth/github" %>
<% end %>